### ISSUE TITLE
 WARN  warning: unplugin-vue-better-define SyntaxError: Cannot resolve TS type: Omit     

### ISSUE THREAD

**Issue by zanderzhg** [ThimoDEV/nuxt-codemirror#100]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.1
- Builder:          -
- User Config:      default
- Runtime Modules:  @pinia/nuxt@0.9.0, @vueuse/nuxt@12.2.0, nuxt-quasar-ui@2.1.7, @unocss/nuxt@0.65.3, @nuxt/eslint@0.7.4, pinia-plugin-persistedstate/nuxt, @nuxtjs/color-mode@3.5.2, @vue-macros/nuxt@1.12.11, nuxt-codemirror@0.0.11

### Reproduction

use nuxt3.15.0

### Describe the bug

 WARN  warning: unplugin-vue-better-define SyntaxError: Cannot resolve TS type: Omit                                    15:34:04  
  Plugin: unplugin-vue-better-define
  File: G:/Programs/XXX/node_modules/.pnpm/nuxt-codemirror@0.0.11_@codemirror+autocomplete@6.18.4_@codemirror+language@6.10.8_@codemirro_zibsxwoirlbnpmayxkwp4jw66a/node_modules/nuxt-codemirror/dist/runtime/components/NuxtCodeMirror.vue

**Comment by ThimoDEV** [comment]
Hello, can you test with the latest release 0.0.12?

Otherwise please make a fork of the playground with a reproduction cause I couldn't reproduce your issue
I updated the playground to 3.15 also

**Comment by zanderzhg** [comment]
thks 👍
